server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/medb2m/config-repo
          default-label: main
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
#          search-paths: config # optional subdirectory inside the repo
  application:
    name: configServer
